name: Update AdGuard Clash Rules

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行 (北京时间早上 8点)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Convert AdGuardHome Rules
      run: |
        ADGUARD_URL="https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt“
        OUTPUT_FILE="adguard_clash_rules.list"

        echo "Downloading AdGuardHome rules from $ADGUARD_URL..."
        curl -s "$ADGUARD_URL" -o temp_adguard_hosts.txt

        if [ $? -ne 0 ]; then
            echo "Error: Failed to download AdGuardHome rules."
            exit 1
        fi

        echo "Converting rules to Clash DOMAIN-SUFFIX format..."
        awk '{
            # 移除 || 前缀和 ^ 后缀 (Adblock Plus / AdGuard 语法)
            gsub(/^\|\|/, "", $1);
            gsub(/\^$/, "", $1);

            # 移除开头的 *. (如果存在的话，例如 *.example.com 变为 example.com)
            gsub(/^\*\./, "", $1);

            # 过滤掉包含斜杠 / 的规则 (表示路径或更复杂的URL规则，Clash DOMAIN-SUFFIX不支持)
            # 过滤掉包含非域名字符的规则 (例如正则表达式，Clash DOMAIN-SUFFIX不支持)
            # 这里只保留看起来像域名的规则（不含 / 且不含非字母数字点划线字符）
            if ($1 !~ /^[#!]|^$|\/|[^\.a-zA-Z0-9-]/) {
                # 再次清理可能残留在末尾的 / (比如 /example.com/)
                gsub(/\/\s*$/, "", $1);
                
                # 检查是否是有效的域名格式（简单检查）
                if ($1 ~ /^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/) {
                    print "DOMAIN-SUFFIX,"$1
                } else {
                    print "# Skipped non-domain rule: " $1 >> "/dev/stderr" # 输出到标准错误，方便调试
                }
            } else {
                print "# Skipped complex rule: " $1 >> "/dev/stderr" # 输出到标准错误，方便调试
            }
        }' temp_adguard_hosts.txt > "$OUTPUT_FILE"

        if [ $? -ne 0 ]; then
            echo "Error: Failed to convert rules."
            exit 1
        fi

        rm temp_adguard_hosts.txt # 清理临时文件

        echo "Clash rules generated: $OUTPUT_FILE"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add adguard_clash_rules.list
        git commit -m "Auto update AdGuard Clash rules" || echo "No changes to commit"
        git push
      env:
        # GITHUB_TOKEN 是 GitHub Actions 自动提供的，无需手动设置
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
