name: Update AdGuard Clash Rules

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行 (北京时间早上 8点)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Convert AdGuardHome Rules
      run: |
        ADGUARD_URL="https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt"
        OUTPUT_FILE="adguard_clash_rules.list"

        echo "Downloading AdGuardHome rules from $ADGUARD_URL..."
        curl -s "$ADGUARD_URL" -o temp_adguard_hosts.txt

        if [ $? -ne 0 ]; then
            echo "Error: Failed to download AdGuardHome rules."
            exit 1
        fi

        echo "Converting rules to Clash DOMAIN-SUFFIX format..."
        # 转换并过滤掉可能为空或注释的行
        awk '{ if ($1 !~ /^#|^!|^$/) print "DOMAIN-SUFFIX,"$1 }' temp_adguard_hosts.txt > "$OUTPUT_FILE"

        if [ $? -ne 0 ]; then
            echo "Error: Failed to convert rules."
            exit 1
        fi

        rm temp_adguard_hosts.txt # 清理临时文件

        echo "Clash rules generated: $OUTPUT_FILE"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add adguard_clash_rules.list
        git commit -m "Auto update AdGuard Clash rules" || echo "No changes to commit"
        git push
      env:
        # GITHUB_TOKEN 是 GitHub Actions 自动提供的，无需手动设置
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
